### ISSUE TITLE
Error on user search id column does not exist

### ISSUE THREAD

**Issue by briangormanly** [agorafoundation/agora#442]
Encounter this error while testing the authUser addition to the api responses: related to #33 and database changes to move id fields to entity_id format.

error: column "id" does not exist
    at Parser.parseErrorMessage (/Users/briangormanly/projects/agora/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/briangormanly/projects/agora/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/briangormanly/projects/agora/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/briangormanly/projects/agora/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 102,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3648',
  routine: 'errorMissingColumn'
}

**Comment by briangormanly** [comment]
Also found this error when search for a workspace by name:
error: column "workspace_name" does not exist
    at Parser.parseErrorMessage (/Users/briangormanly/projects/agora/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/briangormanly/projects/agora/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/briangormanly/projects/agora/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/briangormanly/projects/agora/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
